<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-D2GVCL39" ignored="9" name="Regression" tests="24" failures="8" timestamp="2022-10-12T20:21:05 IST" time="0.217" errors="0">
  <testcase name="sampleATestCase" time="0.005" classname="excelreader.AnnoTations"/>
  <testcase name="sampleBTestCase" time="0.002" classname="excelreader.AnnoTations"/>
  <testcase name="sampleAssertionTestCase" time="0.016" classname="assertions.SoftAssertionInTestNG">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Object is not initialized somewhere expected object to not be null">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Object is not initialized somewhere expected object to not be null
at assertions.SoftAssertionInTestNG.sampleAssertionTestCase(SoftAssertionInTestNG.java:55)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- sampleAssertionTestCase -->
  <testcase name="sampleAssertionTestCase" time="0.002" classname="assertions.AssertionInTestNG">
    <failure type="java.lang.AssertionError" message="Object is not initialized somewhere expected object to not be null">
      <![CDATA[java.lang.AssertionError: Object is not initialized somewhere expected object to not be null
at assertions.AssertionInTestNG.sampleAssertionTestCase(AssertionInTestNG.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- sampleAssertionTestCase -->
  <testcase name="verifyUserCanLoginToApplicationWithValidCredentials" time="0.005" classname="assertions.AssertionInTestNG">
    <failure type="java.lang.AssertionError" message="User profile name is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User profile name is not displayed expected [true] but found [false]
at assertions.AssertionInTestNG.verifyUserCanLoginToApplicationWithValidCredentials(AssertionInTestNG.java:20)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLoginToApplicationWithValidCredentials -->
  <testcase name="verifyUserCanLoginToApplicationWithValidCredentials" time="0.007" classname="assertions.SoftAssertionInTestNG">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	User profile name is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User profile name is not displayed expected [true] but found [false]
at assertions.SoftAssertionInTestNG.verifyUserCanLoginToApplicationWithValidCredentials(SoftAssertionInTestNG.java:24)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLoginToApplicationWithValidCredentials -->
  <testcase name="verifyUserCanNOtLoginToApplicationWithInvalidCredentials" time="0.002" classname="assertions.AssertionInTestNG">
    <failure type="java.lang.AssertionError" message="expected [456.334] but found [456.34]">
      <![CDATA[java.lang.AssertionError: expected [456.334] but found [456.34]
at assertions.AssertionInTestNG.verifyUserCanNOtLoginToApplicationWithInvalidCredentials(AssertionInTestNG.java:35)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanNOtLoginToApplicationWithInvalidCredentials -->
  <testcase name="verifyUserCanNOtLoginToApplicationWithInvalidCredentials" time="0.003" classname="assertions.SoftAssertionInTestNG">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [456.5634] but found [456.34]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [456.5634] but found [456.34]
at assertions.SoftAssertionInTestNG.verifyUserCanNOtLoginToApplicationWithInvalidCredentials(SoftAssertionInTestNG.java:45)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanNOtLoginToApplicationWithInvalidCredentials -->
  <testcase name="verifyUserCanLoginToApplicationWithValidCredentials" time="0.001" classname="invocation.Invocation"/>
  <testcase name="verifySendEmailWillBeDisplayedInSendItem" time="0.002" classname="annotations.testng.AnnotationInTestNG2"/>
  <testcase name="verifyUserCanLoginToApplicationWithValidCredentials" time="0.002" classname="invocation.Invocation"/>
  <testcase name="verifyUserCanLoginToApplicationWithValidCredentials" time="0.001" classname="invocation.Invocation">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at invocation.Invocation.verifyUserCanLoginToApplicationWithValidCredentials(Invocation.java:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLoginToApplicationWithValidCredentials -->
  <testcase name="verifyUserCanSendEmail" time="0.003" classname="annotations.testng.AnnotationInTestNG2"/>
  <testcase name="verifyUserCanLoginToApplicationWithValidCredentials" time="0.001" classname="invocation.Invocation"/>
  <testcase name="verifyUserCanLoginToApplicationWithValidCredentials" time="0.002" classname="invocation.Invocation"/>
  <testcase name="verifyUserCanLoginToApplicationWithValidCredentials" time="0.004" classname="dependent.Dependent"/>
  <testcase name="verifyUserCanLoginToApplicationWithValidCredentials" time="0.001" classname="annotations.testng.AnnotationInTestNG"/>
  <testcase name="verifyUserCanLoginToApplicationWithValidCredentials" time="0.001" classname="enable.EnableClass"/>
  <testcase name="verifyUserCanNOtLoginToApplicationWithInvalidCredentials" time="0.006" classname="annotations.testng.AnnotationInTestNG"/>
  <testcase name="verifyUserCanSendEmail" time="0.001" classname="dependent.Dependent">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dependent.Dependent.verifyUserCanSendEmail(Dependent.java:21)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanSendEmail -->
  <testcase name="A" time="0.002" classname="priority.PriorityInTestNG"/>
  <testcase name="Z" time="0.002" classname="priority.PriorityInTestNG"/>
  <testcase name="verifyUserCanSeeSentEmailInSentBox" time="0.0" classname="dependent.Dependent">
    <skipped/>
  </testcase> <!-- verifyUserCanSeeSentEmailInSentBox -->
  <testcase name="h" time="0.022" classname="priority.PriorityInTestNG"/>
  <testcase name="@BeforeTest beforeTestAnnotation" time="0.0" classname="annotations.testng.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTestAnnotation -->
  <testcase name="@BeforeTest beforeTestAnnotation" time="0.0" classname="annotations.testng.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTestAnnotation -->
  <testcase name="@AfterSuite afterSuiteAnnotation" time="0.0" classname="annotations.testng.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuiteAnnotation -->
  <testcase name="@AfterSuite afterSuiteAnnotation" time="0.0" classname="annotations.testng.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuiteAnnotation -->
  <testcase name="verifyUserCanNOtLoginToApplicationWithInvalidCredentials" time="0.0" classname="enable.EnableClass">
    <ignored/>
  </testcase> <!-- verifyUserCanNOtLoginToApplicationWithInvalidCredentials -->
  <testcase name="@BeforeSuite beforeSuiteAnnotation" time="0.0" classname="annotations.testng.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuiteAnnotation -->
  <testcase name="@BeforeSuite beforeSuiteAnnotation" time="0.0" classname="annotations.testng.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuiteAnnotation -->
  <testcase name="@AfterTest afterTestAnnotation" time="0.0" classname="annotations.testng.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest afterTestAnnotation -->
  <testcase name="@AfterTest afterTestAnnotation" time="0.0" classname="annotations.testng.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest afterTestAnnotation -->
</testsuite> <!-- Regression -->
